# Generated by Django 6.1.1 on 2026-09-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Published', 'published')], default='draft', max_length=20),
        ),
    ]
